<?php
require_once('vendor/autoload.php'); // Include Stripe PHP library

\Stripe\Stripe::setApiKey('pk_test_1234567890abcdefghijklmnopqrstuvwxyz
'); // Set your secret key

// Token generated by Stripe.js
$token = $_POST['stripeToken'];

// Amount in cents
$amount = 5000; // $50

try {
    // Charge the user's card
    $charge = \Stripe\Charge::create(array(
        'amount' => $amount,
        'currency' => 'usd',
        'description' => 'Payment for registration',
        'source' => $token,
    ));

    // Payment successful, proceed with user registration
    // You can add your user registration code here

    echo "Payment successful!";

} catch (\Stripe\Exception\CardException $e) {
    // Card was declined
    echo "Error: " . $e->getMessage();
}
?>
